/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ServiceMapsKeys } from "./components/service-name/facade";
export namespace Components {
    interface ServiceName {
        "service": ServiceMapsKeys;
    }
}
declare global {
    interface HTMLServiceNameElement extends Components.ServiceName, HTMLStencilElement {
    }
    var HTMLServiceNameElement: {
        prototype: HTMLServiceNameElement;
        new (): HTMLServiceNameElement;
    };
    interface HTMLElementTagNameMap {
        "service-name": HTMLServiceNameElement;
    }
}
declare namespace LocalJSX {
    interface ServiceName {
        "service"?: ServiceMapsKeys;
    }
    interface IntrinsicElements {
        "service-name": ServiceName;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "service-name": LocalJSX.ServiceName & JSXBase.HTMLAttributes<HTMLServiceNameElement>;
        }
    }
}
